In [93]:
import pandas as pd

In [94]:
bios = pd.read_csv(r"./athletes/bios.csv")

In [95]:
bios.head(3)
bios.tail(3)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
145497,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,Юлия•Смирнова,NaN
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Goals:

- [  ] Get rid of bullet points in Used names
- [  ] Get rid of extra columns
- [  ] Split height and weight
- [  ] Parse out dates from Born and  Died column
- [  ] Parse out city region an country

In [96]:
df = bios.copy()

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  object
 1   Sex            145500 non-null  object
 2   Full name      145500 non-null  object
 3   Used name      145500 non-null  object
 4   Born           143772 non-null  object
 5   Died           34042 non-null   object
 6   NOC            145499 non-null  object
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  object
 9   Affiliations   95832 non-null   object
 10  Nick/petnames  9145 non-null    object
 11  Title(s)       399 non-null     object
 12  Other names    7167 non-null    object
 13  Nationality    8259 non-null    object
 14  Original name  30739 non-null   object
 15  Name order     7844 non-null    object
dtypes: int64(1), object(15)
memory usage: 17.8+ MB

In [98]:
len(df['Used name'].str.contains('•'))

145500

In [99]:
df['name'] = df['Used name'].str.replace('•',' ')

In [100]:
df.head(5)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet

In [101]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet

In [102]:

df[['Height(cm)','Weight(kg)']]=df['Measurements'].str.split('/',expand=True)

In [103]:
df.head

<bound method NDFrame.head of                                             Roles     Sex  \
0                       Competed in Olympic Games    Male
1                       Competed in Olympic Games    Male
2       Competed in Olympic Games • Administrator    Male
3                       Competed in Olympic Games    Male
4                       Competed in Olympic Games    Male
...                                           ...     ...
145495                  Competed in Olympic Games  Female
145496                  Competed in Olympic Games  Female
145497                  Competed in Olympic Games  Female
145498                  Competed in Olympic Games    Male
145499                Non-starter • Administrator    Male

                                                Full name  \
0       François Joseph Marie Antoine "Jean-François"•...
1                                 Arnaud Benjamin•Boetsch
2                             Jean Laurent Robert•Borotra
3                    Jacques Marie Stanislas Jean•Brugnon
4                                      Henry Albert•Canet
...                                                   ...
145495                                  Polina•Luchnikova
145496                     Valeriya Sergeyevna•Merkusheva
145497                                    Yuliya•Smirnova
145498                                     André•Foussard
145499                      William Berge "Bill"•Phillips

                    Used name  \
0       Jean-François•Blanchy
1              Arnaud•Boetsch
2                Jean•Borotra
3             Jacques•Brugnon
4                Albert•Canet
...                       ...
145495      Polina•Luchnikova
145496    Valeriya•Merkusheva
145497        Yuliya•Smirnova
145498         André•Foussard
145499          Bill•Phillips

                                                     Born  \
0             12 December 1886 in Bordeaux, Gironde (FRA)
1                  1 April 1969 in Meulan, Yvelines (FRA)
2       13 August 1898 in Biarritz, Pyrénées-Atlantiqu...
3                 11 May 1895 in Paris VIIIe, Paris (FRA)
4              17 April 1878 in Wandsworth, England (GBR)
...                                                   ...
145495         30 January 2002 in Serov, Sverdlovsk (RUS)
145496  20 September 1999 in Moskva (Moscow), Moskva (...
145497            8 May 1998 in Kotlas, Arkhangelsk (RUS)
145498            19 May 1899 in Niort, Deux-Sèvres (FRA)
145499  15 July 1913 in Dulwich Hill, New South Wales ...

                                                     Died        NOC  \
0       2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...     France
1                                                     NaN     France
2       17 July 1994 in Arbonne, Pyrénées-Atlantiques ...     France
3                   20 March 1978 in Monaco, Monaco (MON)     France
4                 25 July 1930 in Paris VIIe, Paris (FRA)     France
...                                                   ...        ...
145495                                                NaN        ROC
145496                                                NaN        ROC
145497                                                NaN        ROC
145498          18 March 1986 in Niort, Deux-Sèvres (FRA)     France
145499   20 October 2003 in Sydney, New South Wales (AUS)  Australia

        athlete_id    Measurements  \
0                1             NaN
1                2  183 cm / 76 kg
2                3  183 cm / 76 kg
3                4  168 cm / 64 kg
4                5             NaN
...            ...             ...
145495      149222  167 cm / 61 kg
145496      149223  168 cm / 65 kg
145497      149224  163 cm / 55 kg
145498      149225          166 cm
145499      149814             NaN

                                       Affiliations  \
0                                               NaN
1                Racing Club de France, Paris (FRA)
2                                  TCP, Paris (FRA)
3               Sporting club de Paris, Paris (FRA)
4                                  TCP, Paris (FRA)
...                                             ...
145495                            Agidel, Ufa (RUS)
145496  SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)
145497                            Agidel, Ufa (RUS)
145498                  Beauvoisine FC, Rouen (FRA)
145499                                          NaN

                                     Nick/petnames Title(s) Other names  \
0                                              NaN      NaN         NaN
1                                              NaN      NaN         NaN
2       Le Basque Bondissant (The Bounding Basque)      NaN         NaN
3                                             Toto      NaN         NaN
4                                              NaN      NaN         NaN
...                                            ...      ...         ...
145495                                         NaN      NaN         NaN
145496                                         NaN      NaN         NaN
145497                                         NaN      NaN         NaN
145498                                         NaN      NaN         NaN
145499                                         NaN      NaN         NaN

       Nationality                Original name Name order  \
0              NaN                          NaN        NaN
1              NaN                          NaN        NaN
2              NaN                          NaN        NaN
3              NaN                          NaN        NaN
4              NaN                          NaN        NaN
...            ...                          ...        ...
145495         NaN                          NaN        NaN
145496         NaN  Валерия Сергеевна•Меркушева        NaN
145497         NaN                Юлия•Смирнова        NaN
145498         NaN                          NaN        NaN
145499         NaN                          NaN        NaN

                         name Height(cm) Weight(kg)
0       Jean-François Blanchy        NaN        NaN
1              Arnaud Boetsch    183 cm       76 kg
2                Jean Borotra    183 cm       76 kg
3             Jacques Brugnon    168 cm       64 kg
4                Albert Canet        NaN        NaN
...                       ...        ...        ...
145495      Polina Luchnikova    167 cm       61 kg
145496    Valeriya Merkusheva    168 cm       65 kg
145497        Yuliya Smirnova    163 cm       55 kg
145498         André Foussard     166 cm       None
145499          Bill Phillips        NaN        NaN

[145500 rows x 19 columns]>

In [104]:
df.head(5)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,Height(cm),Weight(kg)
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183 cm,76 kg
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183 cm,76 kg
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168 cm,64 kg
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN

In [105]:
#df.rename(columns={"Weight(kg)":"Height(cm)"}, inplace=True)

df.head(2)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,Height(cm),Weight(kg)
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183 cm,76 kg

In [106]:
#df.drop(columns=['Height(cm)'], inplace=True)

In [107]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,Height(cm),Weight(kg)
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183 cm,76 kg
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183 cm,76 kg
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168 cm,64 kg
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN

In [108]:
#df[['Height(cm)','Weight(Kg)']]=df['Measurements'].str.split('/',expand=True)

In [109]:
df.head(4)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,Height(cm),Weight(kg)
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183 cm,76 kg
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183 cm,76 kg
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168 cm,64 kg

In [110]:
df['Height(cm)'] = df['Height(cm)'].str.strip(' cm')

In [111]:
df.head(5)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,Height(cm),Weight(kg)
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183,76 kg
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183,76 kg
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168,64 kg
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN

In [112]:
df['Weight(kg)'] = df['Weight(kg)'].str.rstrip(' kg')

In [113]:
df.iloc[120]

Roles                               Competed in Olympic Games
Sex                                                      Male
Full name                       Christopher "Chris"•Wilkinson
Used name                                     Chris•Wilkinson
Born             5 January 1970 in Southampton, England (GBR)
Died                                                      NaN
NOC                                             Great Britain
athlete_id                                                121
Measurements                                   180 cm / 72 kg
Affiliations                                              NaN
Nick/petnames                                             NaN
Title(s)                                                  NaN
Other names                                               NaN
Nationality                                               NaN
Original name                                             NaN
Name order                                                NaN
name                                          Chris Wilkinson
Height(cm)                                                180
Weight(kg)                                                 72
Name: 120, dtype: object

In [114]:
df[~df['Measurements'].str.contains('/', na=True)]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,Height(cm),Weight(kg)
87,Competed in Olympic Games • Non-starter,Male,"Hugh Lawrence ""Laurie""•Doherty",Laurie•Doherty,"8 October 1875 in Wimbledon, England (GBR)","21 August 1919 in Broadstairs, England (GBR)",Great Britain,88,178 cm,"All England Lawn Tennis and Croquet Club, Wimb...",Little Do,NaN,NaN,NaN,NaN,NaN,Laurie Doherty,178,None
105,Competed in Olympic Games,Male,Harold Segerson•Mahony,Harold•Mahony,"13 February 1867 in Edinburgh, Scotland (GBR)","27 June 1905 in between Glencar and Killorgin,...",Great Britain,106,191 cm,"Fitzwilliam Lawn Tennis Club, Dublin (IRL)",NaN,NaN,NaN,Ireland,NaN,NaN,Harold Mahony,191,None
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia•Offel,19 December 1971,NaN,Ghana,166,120 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patricia Offel,120 kg,None
242,Competed in Olympic Games,Female,"Lucia Francisca ""Susy""•Susanti Haditono",Susy•Susanti,"11 February 1971 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,243,161 cm,"Jaya Raya, Jakarta (INA)",NaN,NaN,"Wang Lianxiang, 王蓮香",NaN,NaN,NaN,Susy Susanti,161,None
243,Competed in Olympic Games,Female,Lili•Tampi,Lili•Tampi,"19 May 1970 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,244,161 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lili Tampi,161,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145058,Competed in Olympic Games,Male,Daniil Ruslanovich•Serokhvostov,Daniil•Serokhvostov,"4 April 1999 in Barnaul, Altay Kray (RUS)",NaN,ROC,148770,168 cm,NaN,NaN,NaN,NaN,NaN,Даниил Русланович•Серохвостов,NaN,Daniil Serokhvostov,168,None
145096,Competed in Olympic Games,Female,Kamila Valeryevna•Valiyeva,Kamila•Valiyeva,"26 April 2006 in Kazan, Respublika Tatarstan (...",NaN,ROC,148809,160 cm,NaN,NaN,NaN,NaN,NaN,Камила Валерьевна•Валиева,NaN,Kamila Valiyeva,160,None
145163,Competed in Olympic Games,Male,Daniel Andrei•Cacina,Daniel Andrei•Cacina,"17 October 2001 in Brașov, Brașov (ROU)",NaN,Romania,148880,190 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Daniel Andrei Cacina,190,None
145494,Competed in Olympic Games,Male,George Fletcher•Wright,George•Wright,"21 July 1890 in Toronto, Ontario (CAN)","28 January 1973 in Los Angeles, California (USA)",Canada,149221,183 cm,"Argonaut Rowing Club, Toronto (CAN)",NaN,NaN,NaN,NaN,NaN,NaN,George Wright,183,None
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,André Foussard,166,None

In [115]:
df['Weight(kg)'].fillna(df['Height(cm)'], inplace=True)

C:\Users\Limo\AppData\Local\Temp\ipykernel_22180\1496496359.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Weight(kg)'].fillna(df['Height(cm)'], inplace=True)

In [116]:
df.loc[df['Weight(kg)'].str.contains('cm')== True].head(5)[['Measurements','Weight(kg)','Height(cm)']]

Empty DataFrame
Columns: [Measurements, Weight(kg), Height(cm)]
Index: []

In [117]:
import numpy as np
df.loc[df['Weight(kg)'].astype(str).str.contains('cm', na=False),['Weight(kg)']]=np.nan

In [118]:
df.loc[df['Height(cm)'].str.contains('kg')== True].head(5)[['Measurements','Weight(kg)','Height(cm)']]

     Measurements Weight(kg) Height(cm)
165        120 kg     120 kg     120 kg
289         65 kg      65 kg      65 kg
290         76 kg      76 kg      76 kg
1128        71 kg      71 kg      71 kg
1132        60 kg      60 kg      60 kg

In [119]:
df.loc[df['Weight(kg)'].str.contains('cm')== True].head(5)[['Measurements','Weight(kg)','Height(cm)']]

Empty DataFrame
Columns: [Measurements, Weight(kg), Height(cm)]
Index: []

In [120]:
df.loc[df['Height(cm)'].str.contains('kg')== True].head(5)[['Measurements','Weight(kg)','Height(cm)']]

     Measurements Weight(kg) Height(cm)
165        120 kg     120 kg     120 kg
289         65 kg      65 kg      65 kg
290         76 kg      76 kg      76 kg
1128        71 kg      71 kg      71 kg
1132        60 kg      60 kg      60 kg

In [121]:
df.loc[
    df['Height(cm)'].astype(str).str.contains('kg', na=False),
    ['Height(cm)']
] = np.nan

In [122]:
df.loc[df['Height(cm)'].str.contains('kg')== True].head(5)[['Measurements','Weight(kg)','Height(cm)']]

Empty DataFrame
Columns: [Measurements, Weight(kg), Height(cm)]
Index: []

In [123]:
df.head(5)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,Height(cm),Weight(kg)
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183,76
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183,76
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168,64
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN

In [124]:
df.sort_values(['Height(cm)'], ascending=0)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,Height(cm),Weight(kg)
89070,Competed in Olympic Games • Other,Male,Yao•Ming,Yao•Ming,"12 September 1980 in Xuhui District, Shanghai ...",NaN,People's Republic of China,89782,226 cm / 141 kg,"Shanghai Sharks, Shanghai (CHN) / Houston Rock...",NaN,NaN,NaN,NaN,姚•明,Oriental,Yao Ming,226,141
5781,Competed in Olympic Games,Male,"Thomas Loren ""Tommy""•Burleson",Tommy•Burleson,"24 February 1952 in Crossnore, North Carolina ...",NaN,United States,5804,223 cm / 102 kg,"NC State Wolfpack, Raleigh (USA)",NaN,NaN,NaN,NaN,NaN,NaN,Tommy Burleson,223,102
6978,Competed in Olympic Games,Male,Arvydas Romas•Sabonis,Arvydas•Sabonis,"19 December 1964 in Kaunas, Kaunas (LTU)",NaN,Lithuania Soviet Union,7013,223 cm / 122 kg,"Žalgiris Kaunas, Kaunas (LTU) / Real Madrid, M...",Sabas,NaN,"Arvidas Romas Sabonis, Арвидас Ромас Сабонис",Lithuania,NaN,NaN,Arvydas Sabonis,223,122
89075,Competed in Olympic Games,Male,Roberto•Dueñas Hernández,Roberto•Dueñas,"1 November 1975 in Madrid, Madrid (ESP)",NaN,Spain,89787,221 cm / 137 kg,"FC Barcelona, Barcelona (ESP)",NaN,NaN,NaN,NaN,NaN,NaN,Roberto Dueñas,221,137
120266,Competed in Olympic Games,Male,Zhang•Zhaoxu,Zhang•Zhaoxu,"18 November 1987 in Binzhou, Shandong (CHN)",NaN,People's Republic of China,122147,221 cm / 110 kg,"Shanghai Sharks, Shanghai (CHN)",NaN,NaN,NaN,NaN,张•兆旭,Oriental,Zhang Zhaoxu,221,110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,Competed in Olympic Games,Male,Sin•Ye-Chan,Sin•Ye-Chan,13 June 1995,NaN,Republic of Korea,149217,NaN,NaN,NaN,NaN,Shin Ye-Chan,NaN,신•예찬,Oriental,Sin Ye-Chan,NaN,NaN
145491,Competed in Olympic Games,Male,Matthew•Wepke,Matthew•Wepke,5 December 1989,NaN,Jamaica,149218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matthew Wepke,NaN,NaN
145492,Competed in Olympic Games,Male,Carlos•García-Ordóñez Montalvo,Carlos•García-Ordóñez,"24 April 1927 in La Habana (Havana), Ciudad de...","24 November 2019 in Miami, Florida (USA)",Cuba,149219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carlos García-Ordóñez,NaN,NaN
145493,Competed in Olympic Games,Female,Landysh Ilsurovna•Falyakhova,Landysh•Falyakhova,"31 August 1998 in Dva Polya Artash, Respublika...",NaN,ROC,149220,NaN,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",NaN,NaN,NaN,NaN,Ландыш Ильсуровна•Фаляхова,NaN,Landysh Falyakhova,NaN,NaN
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bill Phillips,NaN,NaN

In [128]:
import regex as re
date_pattern = r'\b(\d{1,2}\s+[A-Za-z]{3,9}\s+\d{4}|[A-Za-z]{3,9}\s+\d{1,2},?\s+\d{4}|\d{4}-\d{2}-\d{2}|\d{1,2}/\d{1,2}/\d{4}|(?:18|19|20)\d{2})\b'

df['Born_Date'] = df['Born'].str.extract(date_pattern, flags=re.IGNORECASE)

In [139]:
df.loc[~df['Born_Date'].str.contains(r'.*\d.*', regex=True, na=True)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Used name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, name, Height(cm), Weight(kg), Born_Date]
Index: []

In [142]:
df['Born_Date'] = pd.to_datetime(df['Born_Date'], errors='coerce')

In [143]:
df.Born_Date

0        1886-12-12
1        1969-04-01
2        1898-08-13
3        1895-05-11
4        1878-04-17
            ...
145495   2002-01-30
145496   1999-09-20
145497   1998-05-08
145498   1899-05-19
145499   1913-07-15
Name: Born_Date, Length: 145500, dtype: datetime64[ns]

In [144]:
df['Died_Date'] = df['Died'].str.extract(date_pattern, flags=re.IGNORECASE)

In [147]:
df['Died_Date'] = pd.to_datetime(df['Died_Date'], format="mixed", errors='coerce')

In [148]:
df.head(5)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Title(s),Other names,Nationality,Original name,Name order,name,Height(cm),Weight(kg),Born_Date,Died_Date
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,1886-12-12,1960-10-02
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183,76,1969-04-01,NaT
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jean Borotra,183,76,1898-08-13,1994-07-17
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168,64,1895-05-11,1978-03-20
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN,1878-04-17,1930-07-25

In [150]:
df[['Born_City','Born_Region','Born_Country']] =  df['Born'].str.extract(r'in\s+([^,]+),\s+([^(]+)\s+\(([^)]+)\)',  expand=True)
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,name,Height(cm),Weight(kg),Born_Date,Died_Date,Born_City,Born_Region,Born_Country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,Jean-François Blanchy,NaN,NaN,1886-12-12,1960-10-02,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,Arnaud Boetsch,183,76,1969-04-01,NaT,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,Jean Borotra,183,76,1898-08-13,1994-07-17,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,Jacques Brugnon,168,64,1895-05-11,1978-03-20,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,Albert Canet,NaN,NaN,1878-04-17,1930-07-25,Wandsworth,England,GBR

In [151]:
df.head(20)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,name,Height(cm),Weight(kg),Born_Date,Died_Date,Born_City,Born_Region,Born_Country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,Jean-François Blanchy,NaN,NaN,1886-12-12,1960-10-02,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,Arnaud Boetsch,183,76,1969-04-01,NaT,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,Jean Borotra,183,76,1898-08-13,1994-07-17,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,Jacques Brugnon,168,64,1895-05-11,1978-03-20,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,Albert Canet,NaN,NaN,1878-04-17,1930-07-25,Wandsworth,England,GBR
5,Competed in Olympic Games,Male,Nicolas•Chatelain,Nicolas•Chatelain,"13 January 1970 in Amiens, Somme (FRA)",NaN,France,6,181 cm / 70 kg,"SAG Cestas, Cestas (FRA)",...,NaN,NaN,Nicolas Chatelain,181,70,1970-01-13,NaT,Amiens,Somme,FRA
6,Competed in Olympic Games,Male,Patrick•Chila,Patrick•Chila,"27 November 1969 in Ris-Orangis, Essonne (FRA)",NaN,France,7,180 cm / 73 kg,"AS Pontoise-Cergy TT, Pontoise (FRA) / Royal V...",...,NaN,NaN,Patrick Chila,180,73,1969-11-27,NaT,Ris-Orangis,Essonne,FRA
7,Competed in Olympic Games,Male,Henri Jean•Cochet,Henri•Cochet,"14 December 1901 in Villeurbanne, Rhône (FRA)","2 April 1987 in Saint-Germain-en-Laye, Yveline...",France,8,NaN,NaN,...,NaN,NaN,Henri Cochet,NaN,NaN,1901-12-14,1987-04-02,Villeurbanne,Rhône,FRA
8,Competed in Olympic Games,Male,Marcel•Cousin,Marcel•Cousin,"4 August 1896 in Nîmes, Gard (FRA)","1 August 1986 in Nîmes, Gard (FRA)",France,9,NaN,NaN,...,NaN,NaN,Marcel Cousin,NaN,NaN,1896-08-04,1986-08-01,Nîmes,Gard,FRA
9,Competed in Olympic Games,Male,Luc Henri Hervé Guy•Gardye de la Chapelle,Guy•de la Chapelle,"16 July 1868 in Farges-Allichamps, Cher (FRA)",27 August 1923,France,10,NaN,NaN,...,NaN,NaN,Guy de la Chapelle,NaN,NaN,1868-07-16,1923-08-27,Farges-Allichamps,Cher,FRA
10,Competed in Olympic Games,Male,Élie Marie Gabriel•Dor de Lastours,"Élie, Comte•de Lastours","12 August 1874 in Orgeval, Yvelines (FRA)","18 November 1932 in Castres, Tarn (FRA)",France,11,NaN,NaN,...,NaN,NaN,"Élie, Comte de Lastours",NaN,NaN,1874-08-12,1932-11-18,Orgeval,Yvelines,FRA
11,Competed in Olympic Games • Competed in Interc...,Male,"Maxime Omer Mathieu ""Max""•Omer-Decugis",Max•Decugis,"24 September 1882 in Paris XVIe, Paris (FRA)","6 September 1978 in Biot, Alpes-Maritimes (FRA)",France,12,NaN,Sporting Club de France,...,NaN,NaN,Max Decugis,NaN,NaN,1882-09-24,1978-09-06,Paris XVIe,Paris,FRA
12,Competed in Olympic Games,Male,J.•Defert,J.•Defert,NaN,NaN,France,13,NaN,"Racing Club de France, Paris (FRA)",...,NaN,NaN,J. Defert,NaN,NaN,NaT,NaT,NaN,NaN,NaN
13,Competed in Olympic Games,Male,Étienne•Durand,Étienne•Durand,NaN,NaN,France,14,NaN,"TCP, Paris (FRA)",...,NaN,NaN,Étienne Durand,NaN,NaN,NaT,NaT,NaN,NaN,NaN
14,Competed in Olympic Games,Male,Damien•Éloi,Damien•Éloi,"4 July 1969 in Vire, Calvados (FRA)",NaN,France,15,165 cm / 58 kg,"Caen TTC, Caen (FRA) / SAG Cestas, Cestas (FRA...",...,NaN,NaN,Damien Éloi,165,58,1969-07-04,NaT,Vire,Calvados,FRA
15,Competed in Olympic Games,Male,Marie Joseph Adrien•Fauchier-Magnan,Adrien•Fauchier-Magnan,"19 November 1873 in Paris VIIIe, Paris (FRA)","6 August 1965 in Cannes, Alpes-Maritimes (FRA)",France,16,NaN,NaN,...,NaN,NaN,Adrien Fauchier-Magnan,NaN,NaN,1873-11-19,1965-08-06,Paris VIIIe,Paris,FRA
16,Competed in Olympic Games • Competed in Olympi...,Male,Guy•Forget,Guy•Forget,"4 January 1965 in Casablanca, Casablanca-Setta...",NaN,France,17,189 cm / 79 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,Guy Forget,189,79,1965-01-04,NaT,Casablanca,Casablanca-Settat,MAR
17,Competed in Olympic Games,Male,Jean-Philippe•Gatien,Jean-Philippe•Gatien,"16 October 1968 in Alès, Gard (FRA)",NaN,France,18,178 cm / 73 kg,"Levallois SC, Levallois-Perret (FRA)",...,NaN,NaN,Jean-Philippe Gatien,178,73,1968-10-16,NaT,Alès,Gard,FRA
18,Competed in Olympic Games • Competed in Interc...,Male,Marie Claude Maurice•Germot,Maurice•Germot,"15 November 1882 in Vichy, Allier (FRA)","6 August 1958 in Vichy, Allier (FRA)",France,19,NaN,Sporting Club Vichy,...,NaN,NaN,Maurice Germot,NaN,NaN,1882-11-15,1958-08-06,Vichy,Allier,FRA
19,Competed in Olympic Games,Male,Henry Maurice André•Gobert,André•Gobert,"30 September 1890 in Paris XVIIe, Paris (FRA)","6 December 1951 in Paris VIIe, Paris (FRA)",France,20,NaN,"Sporting Club d'Houlgate, Houlgate (FRA)",...,NaN,NaN,André Gobert,NaN,NaN,1890-09-30,1951-12-06,Paris XVIIe,Paris,FRA

In [152]:

df.columns

Index(['Roles', 'Sex', 'Full name', 'Used name', 'Born', 'Died', 'NOC',
       'athlete_id', 'Measurements', 'Affiliations', 'Nick/petnames',
       'Title(s)', 'Other names', 'Nationality', 'Original name', 'Name order',
       'name', 'Height(cm)', 'Weight(kg)', 'Born_Date', 'Died_Date',
       'Born_City', 'Born_Region', 'Born_Country'],
      dtype='object')

In [155]:
columns_to_keep = ['athlete_id', 'name', 'Born_Date','Born_City', 'Born_Region', 'Born_Country','NOC','Height(cm)', 'Weight(kg)','Died']

df_clean=df[columns_to_keep]

In [156]:
df_clean.to_csv('./clean-data/bios_clean', index=False)